#server:
#  port: 8081
#  servlet:
#    context-path: /
#
#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false
#        show_sql: true
#        hbm2ddl:
#          auto: update
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springsecurity
#    username: root
#    password: root
#
